import java.util.Scanner;

class MyCustomException extends Exception  
{
  MyCustomException (String s1)
  {
	  super(s1);
  }

}  
    
// class that uses custom exception MyCustomException  
public class TestCustomException2  
{  
    // main method  
    public static void main(String args[])  
    {  
        try  
        {  
        	String user ="nandini";
        	String user1=new String("nandini");
        	int password=123;
        	
        	//Scanner s=new Scanner (System.in);
        	//System.out.println("enter username:");
        	//System.out.println("enter password:");
        	
        	//String user1=s.nextLine();
        	//int passcode= s.nextInt();
        	
        	if(user.equals(user1)) 
        	{
        		System.out.println("login success");
        	}
        	else {
        		 throw new MyCustomException("Credentials missmatch, Please enter correct credentials to login into our site");
        	}
            // throw an object of user defined exception  
             
        }  
        catch (MyCustomException ex)  
        {  
        	System.out.println(ex.getMessage());
            System.out.println("Please enter correct credentials");  
              
        }  
  
     //   System.out.println("rest of the code...");    
    }  
}  